steps:
  - id: test-builds-successfully
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
<<<<<<< HEAD
    dir: python-example-noncontainer-artifacts/
=======
    dir: python-example-flask/
>>>>>>> origin/pr/122
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud builds submit --config cloudbuild.yaml \
<<<<<<< HEAD
        --substitutions SHORT_SHA=${SHORT_SHA},_ARTIFACT_REGISTRY_PYTHON_REPO=${_ARTIFACT_REGISTRY_PYTHON_REPO},_BUCKET_NAME=${_BUCKET_NAME}
=======
        --substitutions SHORT_SHA=${SHORT_SHA},_ARTIFACT_REGISTRY_REPO=${_ARTIFACT_REGISTRY_REPO},_BUCKET_NAME=${_BUCKET_NAME}
>>>>>>> origin/pr/122

  - id: cleanup
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
<<<<<<< HEAD
        gcloud storage rm gs://${_BUCKET_NAME}/${SHORT_SHA}_test_log.xml
        gcloud artifacts versions delete 0.0.1 -q --package python-example-noncontainer-artifacts --repository $_ARTIFACT_REGISTRY_PYTHON_REPO --location us-central1
=======
        gsutil rm gs://${_BUCKET_NAME}/${SHORT_SHA}_test_log.xml
        gcloud artifacts docker images delete us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}
        gcloud run services delete helloworld-${SHORT_SHA} --region us-central1 --quiet
>>>>>>> origin/pr/122
